package main

import (
 "bytes"; "crypto/rand"; "encoding/json"; "errors"; "fmt"; "html"; "io"; "log"; "math/big"; "net"; "net/http"; "net/url"; "os"; "path/filepath"; "regexp"; "sort"; "strconv"; "strings"; "sync"; "time"
)
type config struct{ ListenAddr,GarageURL,GarageUser,GaragePassword,HotspotServer,GuestRateLimit,AdminUser,AdminPassword,LogPath string; GrantMinutes int; RequestTTL time.Duration; AdminCIDR *net.IPNet }
type request struct{ ID,ClientIP,MAC string; CreatedAt,ExpiresAt time.Time }
type app struct{ cfg config; router client; mu sync.Mutex; pending map[string]request }
type client struct{ base,user,pass string; http *http.Client }
var macRE=regexp.MustCompile(`^[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){5}$`)
func main(){ a:=newApp(); go a.cleanup(); m:=http.NewServeMux(); m.HandleFunc("/health",a.health); m.HandleFunc("/",a.home); m.HandleFunc("/request",a.request); m.HandleFunc("/status",a.status); m.HandleFunc("/admin",a.admin); m.HandleFunc("/approve",a.approve); log.Fatal(http.ListenAndServe(a.cfg.ListenAddr,m)) }
func newApp()*app{ _,cidr,_:=net.ParseCIDR(env("ADMIN_CIDR","192.168.50.0/24")); c:=config{ListenAddr:env("LISTEN_ADDR",":8080"),GarageURL:strings.TrimRight(env("GARAGE_ROUTER_URL","http://192.168.50.1"),"/"),GarageUser:env("GARAGE_ROUTER_USER","approval-api"),GaragePassword:env("GARAGE_ROUTER_PASSWORD",""),HotspotServer:env("HOTSPOT_SERVER","hotspot-guest"),GuestRateLimit:env("GUEST_RATE_LIMIT","5M/20M"),GrantMinutes:num("GRANT_MINUTES",60),RequestTTL:time.Duration(num("REQUEST_TTL_SECONDS",600))*time.Second,AdminUser:env("ADMIN_USER","master"),AdminPassword:env("ADMIN_PASSWORD",""),AdminCIDR:cidr,LogPath:env("LOG_PATH","/data/approval.log")}; return &app{cfg:c,router:client{base:c.GarageURL,user:c.GarageUser,pass:c.GaragePassword,http:&http.Client{Timeout:12*time.Second}},pending:map[string]request{}} }
func env(k,d string)string{if v:=strings.TrimSpace(os.Getenv(k));v!=""{return v};return d}
func num(k string,d int)int{n,e:=strconv.Atoi(env(k,""));if e!=nil||n<1{return d};return n}
func (a *app)health(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/plain");w.Write([]byte("OK"))}
func (a *app)home(w http.ResponseWriter,r *http.Request){if r.URL.Path!="/" {http.NotFound(w,r);return}; ip,mac:=formCtx(r); a.page(w,"Гостевой Wi-Fi",fmt.Sprintf(`<h1>Гостевой Wi-Fi</h1><p>Отправьте заявку мастеру. Доступ будет открыт после подтверждения.</p><form method="post" action="/request"><input type="hidden" name="client_ip" value="%s"><input type="hidden" name="mac" value="%s"><button>Запросить доступ</button></form>`,html.EscapeString(ip),html.EscapeString(mac)))}
func (a *app)request(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{http.Redirect(w,r,"/",303);return};r.ParseForm();ip,mac:=formCtx(r);if !validIP(ip){a.err(w,"Не удалось определить устройство.");return};a.mu.Lock();for _,q:=range a.pending{if q.ClientIP==ip&&q.MAC==mac&&time.Now().Before(q.ExpiresAt){a.mu.Unlock();http.Redirect(w,r,"/status?id="+q.ID,303);return}};id,e:=id();if e==nil{a.pending[id]=request{id,ip,mac,time.Now().UTC(),time.Now().Add(a.cfg.RequestTTL).UTC()}};a.mu.Unlock();if e!=nil{a.err(w,"Не удалось создать заявку.");return};a.log(map[string]any{"type":"request_created","request_id":id,"client_ip":ip,"mac":mac});http.Redirect(w,r,"/status?id="+id,303)}
func (a *app)status(w http.ResponseWriter,r *http.Request){id:=r.URL.Query().Get("id");a.mu.Lock();q,ok:=a.pending[id];a.mu.Unlock();if !ok||time.Now().After(q.ExpiresAt){a.err(w,"Заявка не найдена или устарела.");return};a.page(w,"Ожидание",fmt.Sprintf(`<h1>Заявка принята</h1><p>Покажите мастеру номер: <strong>%s</strong>.</p><p>Страница обновляется автоматически.</p><script>setTimeout(()=>location.reload(),5000)</script>`,html.EscapeString(id)))}
func (a *app)admin(w http.ResponseWriter,r *http.Request){if !a.auth(w,r){return};a.mu.Lock();xs:=make([]request,0,len(a.pending));for _,q:=range a.pending{if time.Now().Before(q.ExpiresAt){xs=append(xs,q)}};a.mu.Unlock();sort.Slice(xs,func(i,j int)bool{return xs[i].CreatedAt.Before(xs[j].CreatedAt)});var b strings.Builder;b.WriteString("<h1>Заявки на Wi-Fi</h1>");if len(xs)==0{b.WriteString("<p>Активных заявок нет.</p>")};for _,q:=range xs{fmt.Fprintf(&b,`<section><strong>%s</strong><br>Устройство: %s / %s<form method="post" action="/approve"><input type="hidden" name="id" value="%s"><input name="order_ref" maxlength="64" placeholder="Номер заказа или госномер" required><button>Подтвердить доступ</button></form></section>`,html.EscapeString(q.ID),html.EscapeString(q.ClientIP),html.EscapeString(q.MAC),html.EscapeString(q.ID))};a.page(w,"Подтверждение Wi-Fi",b.String())}
func (a *app)approve(w http.ResponseWriter,r *http.Request){if !a.auth(w,r){return};if r.Method!="POST"{http.Redirect(w,r,"/admin",303);return};r.ParseForm();id,ref:=strings.TrimSpace(r.FormValue("id")),strings.TrimSpace(r.FormValue("order_ref"));if ref==""||len(ref)>64{a.err(w,"Укажите номер заказа или госномер.");return};a.mu.Lock();q,ok:=a.pending[id];if ok{delete(a.pending,id)};a.mu.Unlock();if !ok||time.Now().After(q.ExpiresAt){a.err(w,"Заявка устарела.");return};if e:=a.grant(q);e!=nil{a.log(map[string]any{"type":"grant_error","request_id":id,"client_ip":q.ClientIP,"mac":q.MAC,"order_ref":ref,"error":e.Error()});a.err(w,"Доступ выдать не удалось. SMS-доступ не изменён.");return};u,_,_:=r.BasicAuth();a.log(map[string]any{"type":"auth_approved","request_id":id,"client_ip":q.ClientIP,"mac":q.MAC,"order_ref":ref,"operator":u});a.page(w,"Готово",fmt.Sprintf("<h1>Готово</h1><p>Доступ открыт на %d минут.</p>",a.cfg.GrantMinutes))}
func (a *app)auth(w http.ResponseWriter,r *http.Request)bool{host,_,e:=net.SplitHostPort(r.RemoteAddr);if e!=nil||a.cfg.AdminCIDR==nil||!a.cfg.AdminCIDR.Contains(net.ParseIP(host)){http.NotFound(w,r);return false};u,p,ok:=r.BasicAuth();if !ok||a.cfg.AdminPassword==""||u!=a.cfg.AdminUser||p!=a.cfg.AdminPassword{w.Header().Set("WWW-Authenticate",`Basic realm="Garage Wi-Fi"`);http.Error(w,"authorization required",401);return false};return true}
func (a *app)grant(q request)error{if a.cfg.GaragePassword==""{return errors.New("GARAGE_ROUTER_PASSWORD is empty")};if !macRE.MatchString(q.MAC){return errors.New("device MAC is required")};x:=time.Now().Add(time.Duration(a.cfg.GrantMinutes)*time.Minute).Unix();c:=fmt.Sprintf("local-auth expires=%d",x);name:="local-auth-"+strings.ReplaceAll(strings.ToLower(q.MAC),":","");if e:=a.router.put("/queue/simple",map[string]string{"name":name,"target":q.ClientIP+"/32","max-limit":a.cfg.GuestRateLimit,"comment":c+" mac="+q.MAC});e!=nil{return e};return a.router.put("/ip/hotspot/ip-binding",map[string]string{"server":a.cfg.HotspotServer,"address":q.ClientIP,"mac-address":q.MAC,"type":"bypassed","comment":c})}
func (c client)put(path string,b any)error{raw,e:=json.Marshal(b);if e!=nil{return e};r,e:=http.NewRequest("PUT",c.base+"/rest"+path,bytes.NewReader(raw));if e!=nil{return e};r.SetBasicAuth(c.user,c.pass);r.Header.Set("Content-Type","application/json");z,e:=c.http.Do(r);if e!=nil{return e};defer z.Body.Close();if z.StatusCode>=300{return fmt.Errorf("%s",z.Status)};return nil}
func (c client)get(path string,out any)error{r,e:=http.NewRequest("GET",c.base+"/rest"+path,nil);if e!=nil{return e};r.SetBasicAuth(c.user,c.pass);z,e:=c.http.Do(r);if e!=nil{return e};defer z.Body.Close();if z.StatusCode>=300{return fmt.Errorf("%s",z.Status)};return json.NewDecoder(z.Body).Decode(out)}
func (c client)delete(path string)error{r,e:=http.NewRequest("DELETE",c.base+"/rest"+path,nil);if e!=nil{return e};r.SetBasicAuth(c.user,c.pass);z,e:=c.http.Do(r);if e!=nil{return e};defer z.Body.Close();if z.StatusCode>=300{return fmt.Errorf("%s",z.Status)};return nil}
func formCtx(r *http.Request)(string,string){ip:=r.FormValue("client_ip");if !validIP(ip){h,_,_:=net.SplitHostPort(r.RemoteAddr);ip=h};return ip,mac(r.FormValue("mac"))}
func validIP(v string)bool{return net.ParseIP(strings.TrimSpace(v))!=nil}
func mac(v string)string{v=strings.ToUpper(strings.TrimSpace(v));if macRE.MatchString(v){return v};return ""}
func id()(string,error){n,e:=rand.Int(rand.Reader,big.NewInt(900000));return fmt.Sprintf("G-%06d",n.Int64()+100000),e}
func(a *app)cleanup(){a.cleanupOnce();t:=time.NewTicker(time.Minute);defer t.Stop();for range t.C{a.cleanupOnce()}}
func(a *app)cleanupOnce(){now:=time.Now();a.mu.Lock();for k,q:=range a.pending{if now.After(q.ExpiresAt){delete(a.pending,k);a.log(map[string]any{"type":"request_expired","request_id":k,"client_ip":q.ClientIP,"mac":q.MAC})}};a.mu.Unlock();if e:=a.cleanupExpiredGrants(now.Unix());e!=nil{log.Printf("local-auth cleanup: %v",e)}}
func(a *app)cleanupExpiredGrants(now int64)error{if a.cfg.GaragePassword==""{return nil};for _,path:=range []string{"/queue/simple","/ip/hotspot/ip-binding"}{var items []map[string]any;if e:=a.router.get(path,&items);e!=nil{return e};for _,item:=range items{if !expiredLocalAuth(item,now){continue};id,ok:=item[".id"].(string);if !ok||id==""{continue};if e:=a.router.delete(path+"/"+url.PathEscape(id));e!=nil{return e}}};return nil}
func expiredLocalAuth(item map[string]any,now int64)bool{comment,ok:=item["comment"].(string);if !ok||!strings.HasPrefix(comment,"local-auth "){return false};for _,part:=range strings.Fields(comment){if !strings.HasPrefix(part,"expires="){continue};until,e:=strconv.ParseInt(strings.TrimPrefix(part,"expires="),10,64);return e==nil&&until<=now};return false}
func(a *app)log(v map[string]any){v["time_utc"]=time.Now().UTC().Format(time.RFC3339Nano);b,e:=json.Marshal(v);if e!=nil{return};d:=filepath.Dir(a.cfg.LogPath);if os.MkdirAll(d,0755)!=nil{return};f,e:=os.OpenFile(filepath.Join(d,"approval-"+time.Now().UTC().Format("2006-01")+".jsonl"),os.O_APPEND|os.O_CREATE|os.O_WRONLY,0644);if e==nil{defer f.Close();f.Write(append(b,'\n'))}}
func(a *app)err(w http.ResponseWriter,s string){a.page(w,"Ошибка","<h1>Ошибка</h1><p>"+html.EscapeString(s)+"</p>")}
func(a *app)page(w http.ResponseWriter,title,body string){w.Header().Set("Content-Type","text/html; charset=utf-8");fmt.Fprintf(w,`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#f3f4f6;font:17px Arial;color:#111}main{max-width:420px;margin:36px auto;background:#fff;padding:24px;border-radius:10px}input,button{width:100%%;box-sizing:border-box;font-size:17px;padding:13px;margin-top:12px}button{border:0;border-radius:8px;background:#1677ff;color:white}section{border-top:1px solid #ddd;padding:14px 0}</style><main><title>%s</title>%s</main>`,html.EscapeString(title),body)}
var _=io.EOF; var _=url.Values{}
